root_dir : /media/aolab/untitiled/workspace/RIF
model_name : resnet50
batch_size : 64
num_workers : 16
num_sanity_val_steps : 4
input_size : 224
out_features : 2
learning_rate : 0.003
early_stopping_metric : val_loss
pretrained : True
max_epocks : 15
min_epocks : 10
gpus : [0]
output_path : str
name : train_model
wandb : True
train : True
log_every_n_steps : 4
split : False
test : False
opt : False
semi : True
iteration : 2
makevideo : True
remove : False
video_name : video09